
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_system_development

test:
  <<: *default
  database: task_system_test
  
production:
  <<: *default
  database: task_system_production
  username: task_system
  password: <%= ENV['TASK_SYSTEM_DATABASE_PASSWORD'] %>
